"""
Define the default configuration for the Backup Program on Linux.

File:       default_config.py
Author:     Lorn B Kerr
Copyright:  (c) 2022,2023 Lorn B Kerr
License:    MIT, see file LICENSE
Version:    1.0.1
"""

import os

file_name = "default_config.py"
file_version = "1.1.0"
changes = {
    "1.0.0": "Initial release",
    "1.1.0": "Removed unused cloud options and config values;"
    + "Removed unnecessary section headers to make a single level dict;"
    + "Corrected 'base_dir' to 'start_dir'.",
}

default_config = {
    # Time stamp of the last backup. Default of '0' means never.
    "last_backup": "-",

    # What is the base directory to start scanning for changed
    # files. By default, it is the 'user_id' dir, '/home/{user_id}' on linux
    # or 'C:\Users\{user_id}' on Windows.
    "start_dir": os.path.expanduser('~'),

    # Where is the backup location (directory or drive)? For a usb
    # drive, Fedora Linux is '/run/media/*backup_location*', Windows
    # will be a drive letter, generally 'E:' or greater.
    "backup_location": "",

    # The backup log file name
    "log_file": "backup_log.db",

    # What directories and files do we want to exclude from the backup?
    # In general operation, areas like the various cache and trash
    # directories are volatile and probably don't need backup. Other
    # specific directories can also be specified.

    # cache directories generally have the form '*/*cache*/'
    "exclude_cache_dir": True,

    # trash bins have the form '*/*trash*/
    "exclude_trash_dir": True,

    # download directories are usually transient; download something and
    # then put it where it belongs, so maybe no backup needed.
    "exclude_download_dir": True,

    # Don't save the Windows 'System Volume Information'.
    # This backup program is not designed to back up the system os
    # files so this should not ba copied.
    "sysvolinfo_dir": True,

    # Specific directories can be noted for exclusion as desired.
    "exclude_specific_dirs": [
        "venv",  # python virtual environment should be regenerated,
        "tox",   # tox directories should be regenerated as needed
    ],

    # What specific files do we want to exclude from backup.
    # Don't need standard backup files generated by various
    # programs with signatures like '*~' and '*.bak'
    "exclude_backup_files": True,

    # Some programs use a single file for for the 'cache' rather
    # than a directory. Exclude these files if True
    #"exclude_cache_files": True,
    #'Can't really find instances of this that are useful, so delete for now.

    # Specific files can be noted for exclusion as desired.
    "exclude_specific_files": [],

    # What specific directories and files do we want to include in the
    # backup that would otherwise be excluded? Specific directories and
    # files can be specified.

    # Set of named directories to include.
    "include_specific_dirs": [],

    # Set of named  files to include.
    "include_specific_files": [],
}
